# .github/workflows/dotnet.yml
name: .NET Core CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Change if you're using another version

    - name: Restore dependencies
      run: dotnet restore Homy.sln

    - name: Build
      run: dotnet build Homy.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test Homy.sln --no-build --verbosity normal
